server:
  port: 8083

topic:
  name: t.food.order

spring:
  kafka:
    consumer:
      group-id: "default"

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:postgresql://localhost:5432/kafka_practice
    username: postgres
    password: edvdrm2004

  jpa:
    hibernate:
      ddl-auto: update